### ISSUE TITLE
v1 Tracking Issue

### ISSUE THREAD

**Issue by finn-orsini** [wayfair/one-version#4]
Before releasing v1, complete the following:  

- [ ] https://github.com/wayfair-incubator/one-version/issues/7
- [ ] https://github.com/wayfair-incubator/one-version/issues/6
- [ ] https://github.com/wayfair-incubator/one-version/issues/5 
- [x] https://github.com/wayfair-incubator/one-version/issues/9
